const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const playerSchema = new Schema({
  chance_of_playing_next_round: Number,
  chance_of_playing_this_round: Number,
  code: Number,
  cost_change_event: Number,
  cost_change_event_fall: Number,
  cost_change_start: Number,
  cost_change_start_fall: Number,
  dreamteam_count: Number,
  element_type: Number,
  ep_next: String,
  ep_this: String,
  event_points: Number,
  first_name: String,
  form: String,
  id: Number,
  in_dreamteam: Boolean,
  news: String,
  news_added: String,
  now_cost: Number,
  photo: String,
  points_per_game: String,
  second_name: String,
  selected_by_percent: String,
  special: Boolean,
  squad_number: Number,
  status: String,
  team: Number,
  team_code: Number,
  total_points: Number,
  transfers_in: Number,
  transfers_in_event: Number,
  transfers_out: Number,
  transfers_out_event: Number,
  value_form: String,
  value_season: String,
  web_name: String,
  minutes: Number,
  goals_scored: Number,
  assists: Number,
  clean_sheets: Number,
  goals_conceded: Number,
  own_goals: Number,
  penalties_saved: Number,
  penalties_missed: Number,
  yellow_cards: Number,
  red_cards: Number,
  saves: Number,
  bonus: Number,
  bps: Number,
  influence: String,
  creativity: String,
  threat: String,
  ict_index: String,
  influence_rank: Number,
  influence_rank_type: Number,
  creativity_rank: Number,
  creativity_rank_type: Number,
  threat_rank: Number,
  threat_rank_type: Number,
  ict_index_rank: Number,
  ict_index_rank_type: Number,
  corners_and_indirect_freekicks_order: Number,
  corners_and_indirect_freekicks_text: String,
  direct_freekicks_order: Number,
  direct_freekicks_text: String,
  penalties_order: String,
  penalties_text: String,
});

module.exports = mongoose.model('Player', playerSchema);
