#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=11
TOTAL_MINUTES=35

if [[ "${1:-}" == "--" ]]; then
  shift
fi

TARGET="${1:-}"
SOURCE_SEASON="25-26"
SOURCE_DISPLAY_NAME="2025/26"
TARGET_SEASON="26-27"
FINAL_GAMEWEEK=38

if [[ "$TARGET" != "staging" && "$TARGET" != "production" ]]; then
  printf 'Usage: pnpm release:season -- staging|production\n' >&2
  exit 1
fi

require_confirmation() {
  if ! confirm "$1"; then
    warn "release stopped"
    exit 1
  fi
}

require_positive_integer() {
  if [[ ! "$2" =~ ^[0-9]+$ ]] || (( $2 < 1 )); then
    warn "$1 must be a positive integer"
    exit 1
  fi
}

call_sync_endpoint() {
  local endpoint="$1" count_field="$2" expected_count="${3:-}" response count
  response=$(curl --fail-with-body --silent --show-error \
    --request POST \
    --header "x-api-key: $RELEASE_SYNC_API_KEY" \
    "$RELEASE_APP_URL/api/$endpoint")
  printf '  %s\n' "$response"
  count=$(printf '%s' "$response" | node -e '
    let input = "";
    process.stdin.on("data", chunk => input += chunk);
    process.stdin.on("end", () => {
      const value = JSON.parse(input)[process.argv[1]];
      if (!Number.isInteger(value)) process.exit(1);
      process.stdout.write(String(value));
    });
  ' "$count_field")
  require_positive_integer "$count_field" "$count"
  if [[ -n "$expected_count" && "$count" -ne "$expected_count" ]]; then
    warn "$endpoint returned $count; expected $expected_count"
    exit 1
  fi
}

banner "2026/27 season release — $TARGET"

stage "Confirm the target" 2
say "This run will archive $SOURCE_DISPLAY_NAME and clear operational data in $TARGET."
say "Current commit: $(git rev-parse --short HEAD 2>/dev/null || printf 'unknown')"
ask RELEASE_APP_URL "Enter the deployed $TARGET application URL:"
RELEASE_APP_URL="${RELEASE_APP_URL%/}"
ask RELEASE_SUPABASE_PROJECT_REF "Enter the $TARGET Supabase project reference:"
ask RELEASE_TARGET_CONFIRMATION "Type $TARGET to confirm the target:"
if [[ "$RELEASE_TARGET_CONFIRMATION" != "$TARGET" ]]; then
  warn "target confirmation did not match"
  exit 1
fi
require_confirmation "Is this exact application commit deployed to $TARGET?"

stage "Close writes and pause the cron" 4
open_url "https://supabase.com/dashboard/project/$RELEASE_SUPABASE_PROJECT_REF/sql/new"
say "Run this command to close team registration without a deployment:"
printf "\n  update public.settings\n"
printf "  set setting_value = 'false', updated_at = now()\n"
printf "  where setting_key = 'team_registration_open';\n\n"
open_url "https://dash.cloudflare.com/"
step "Disable the scheduled player-sync trigger for $TARGET."
require_confirmation "Is registration closed and the player cron paused?"

stage "Confirm the backup" 3
open_url "https://supabase.com/dashboard/project/$RELEASE_SUPABASE_PROJECT_REF/database/backups"
step "Confirm a restorable backup exists from immediately before this release."
require_confirmation "Have you verified the backup for $TARGET?"

stage "Archive $SOURCE_DISPLAY_NAME" 5
open_url "https://supabase.com/dashboard/project/$RELEASE_SUPABASE_PROJECT_REF/sql/new"
say "Run this owner-only command in the SQL Editor:"
printf "\n  select * from public.archive_completed_season('%s', '%s', %s);\n\n" \
  "$SOURCE_SEASON" "$SOURCE_DISPLAY_NAME" "$FINAL_GAMEWEEK"
ask ARCHIVED_TEAM_COUNT "Enter the returned team_count:"
ask ARCHIVED_PLAYER_COUNT "Enter the returned player_count:"
ask ARCHIVED_TRANSFER_COUNT "Enter the returned transfer_count:"
require_positive_integer "team_count" "$ARCHIVED_TEAM_COUNT"
require_positive_integer "player_count" "$ARCHIVED_PLAYER_COUNT"
if [[ ! "$ARCHIVED_TRANSFER_COUNT" =~ ^[0-9]+$ ]]; then
  warn "transfer_count must be zero or a positive integer"
  exit 1
fi
if (( ARCHIVED_PLAYER_COUNT != ARCHIVED_TEAM_COUNT * 11 )); then
  warn "archive does not contain exactly 11 players per team"
  exit 1
fi

stage "Clear operational data" 3
warn "This is the destructive step. The immutable archive and backup are the recovery paths."
ask CLEAR_CONFIRMATION "Type CLEAR $TARGET to authorize deletion:"
if [[ "$CLEAR_CONFIRMATION" != "CLEAR $TARGET" ]]; then
  warn "clear confirmation did not match"
  exit 1
fi
say "Run this command in the already-open $TARGET SQL Editor:"
printf "\n  select * from public.clear_archived_season_operational_data('%s');\n\n" \
  "$SOURCE_SEASON"
ask CLEARED_TEAM_COUNT "Enter the returned drafted_team_count:"
ask CLEARED_PLAYER_COUNT "Enter the returned drafted_player_count:"
ask CLEARED_TRANSFER_COUNT "Enter the returned transfer_count:"
if [[ "$CLEARED_TEAM_COUNT" != "$ARCHIVED_TEAM_COUNT" \
  || "$CLEARED_PLAYER_COUNT" != "$ARCHIVED_PLAYER_COUNT" \
  || "$CLEARED_TRANSFER_COUNT" != "$ARCHIVED_TRANSFER_COUNT" ]]; then
  warn "clear counts do not match the archive counts"
  exit 1
fi

stage "Authenticate the import" 1
ask_secret RELEASE_SYNC_API_KEY "Enter the $TARGET SYNC_API_KEY:"
if [[ -z "$RELEASE_SYNC_API_KEY" ]]; then
  warn "SYNC_API_KEY cannot be blank"
  exit 1
fi

stage "Import 20 clubs" 2
call_sync_endpoint "sync-teams" "teamsCount" 20

stage "Import current players" 3
call_sync_endpoint "sync-players" "playersCount"

stage "Import 380 fixtures" 3
call_sync_endpoint "sync-fixtures" "fixturesCount" 380

stage "Verify the database" 4
open_url "https://supabase.com/dashboard/project/$RELEASE_SUPABASE_PROJECT_REF/sql/new"
say "Run this verification query:"
printf "\n  select 'clubs' as item, count(*) from public.teams\n"
printf "  union all select 'players', count(*) from public.players\n"
printf "  union all select 'fixtures', count(*) from public.fixtures\n"
printf "  union all select 'active fantasy teams', count(*) from public.drafted_teams\n"
printf "  union all select 'archived seasons', count(*) from public.seasons where archived_at is not null;\n\n"
step "Expect 20 clubs, 380 fixtures, more than zero players, zero active fantasy teams, and the archived Season."
require_confirmation "Do the database counts and archived standings look correct?"

stage "Open 2026/27 and smoke test" 4
open_url "https://supabase.com/dashboard/project/$RELEASE_SUPABASE_PROJECT_REF/sql/new"
ask RELEASE_SITE_OPEN "Should the public site be open after release? Enter true or false:"
if [[ "$RELEASE_SITE_OPEN" != "true" && "$RELEASE_SITE_OPEN" != "false" ]]; then
  warn "site_open must be true or false"
  exit 1
fi
say "Run this command to switch the application to the new Season atomically:"
printf "\n  update public.settings\n"
printf "  set setting_value = case setting_key\n"
printf "    when 'active_season' then '%s'\n" "$TARGET_SEASON"
printf "    when 'current_gameweek' then '1'\n"
printf "    when 'season_complete' then 'false'\n"
printf "    when 'site_open' then '%s'\n" "$RELEASE_SITE_OPEN"
printf "    when 'team_registration_open' then 'true'\n"
printf "  end, updated_at = now()\n"
printf "  where setting_key in (\n"
printf "    'active_season', 'current_gameweek', 'season_complete',\n"
printf "    'site_open', 'team_registration_open'\n"
printf "  );\n\n"
pause "Press Enter after the settings update has completed."
curl --fail-with-body --silent --show-error "$RELEASE_APP_URL/" >/dev/null
curl --fail-with-body --silent --show-error "$RELEASE_APP_URL/team-builder" >/dev/null
say "The welcome page and team builder both responded successfully."
step "Submit one test team and confirm the appropriate admin workflow manually."
require_confirmation "Did the $TARGET smoke test pass?"

stage "Resume scheduled updates" 1
open_url "https://dash.cloudflare.com/"
step "Re-enable the scheduled player-sync trigger for $TARGET."
require_confirmation "Is the player cron enabled again?"

finish
