create table "public"."fixtures" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "game_week" integer not null,
    "home_team" integer not null,
    "away_team" integer not null,
    "home_team_score" integer not null,
    "away_team_score" integer not null
);


CREATE UNIQUE INDEX fixtures_pkey ON public.fixtures USING btree (id);

alter table "public"."fixtures" add constraint "fixtures_pkey" PRIMARY KEY using index "fixtures_pkey";

alter table "public"."fixtures" add constraint "public_fixtures_away_team_fkey" FOREIGN KEY (away_team) REFERENCES teams(id) not valid;

alter table "public"."fixtures" validate constraint "public_fixtures_away_team_fkey";

alter table "public"."fixtures" add constraint "public_fixtures_home_team_fkey" FOREIGN KEY (home_team) REFERENCES teams(id) not valid;

alter table "public"."fixtures" validate constraint "public_fixtures_home_team_fkey";

grant delete on table "public"."fixtures" to "anon";

grant insert on table "public"."fixtures" to "anon";

grant references on table "public"."fixtures" to "anon";

grant select on table "public"."fixtures" to "anon";

grant trigger on table "public"."fixtures" to "anon";

grant truncate on table "public"."fixtures" to "anon";

grant update on table "public"."fixtures" to "anon";

grant delete on table "public"."fixtures" to "authenticated";

grant insert on table "public"."fixtures" to "authenticated";

grant references on table "public"."fixtures" to "authenticated";

grant select on table "public"."fixtures" to "authenticated";

grant trigger on table "public"."fixtures" to "authenticated";

grant truncate on table "public"."fixtures" to "authenticated";

grant update on table "public"."fixtures" to "authenticated";

grant delete on table "public"."fixtures" to "service_role";

grant insert on table "public"."fixtures" to "service_role";

grant references on table "public"."fixtures" to "service_role";

grant select on table "public"."fixtures" to "service_role";

grant trigger on table "public"."fixtures" to "service_role";

grant truncate on table "public"."fixtures" to "service_role";

grant update on table "public"."fixtures" to "service_role";


