create table "public"."player_statistics" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "player_id" integer not null,
    "fixture_id" bigint not null,
    "goals" integer,
    "assists" integer,
    "red_card" boolean,
    "clean_sheet" boolean,
    "author" uuid not null default gen_random_uuid(),
    "points" integer not null
);


CREATE UNIQUE INDEX player_statistics_pkey ON public.player_statistics USING btree (id);

alter table "public"."player_statistics" add constraint "player_statistics_pkey" PRIMARY KEY using index "player_statistics_pkey";

alter table "public"."player_statistics" add constraint "public_player_statistics_author_fkey" FOREIGN KEY (author) REFERENCES auth.users(id) not valid;

alter table "public"."player_statistics" validate constraint "public_player_statistics_author_fkey";

alter table "public"."player_statistics" add constraint "public_player_statistics_fixture_id_fkey" FOREIGN KEY (fixture_id) REFERENCES fixtures(id) not valid;

alter table "public"."player_statistics" validate constraint "public_player_statistics_fixture_id_fkey";

alter table "public"."player_statistics" add constraint "public_player_statistics_player_id_fkey" FOREIGN KEY (player_id) REFERENCES players(player_id) not valid;

alter table "public"."player_statistics" validate constraint "public_player_statistics_player_id_fkey";

grant delete on table "public"."player_statistics" to "anon";

grant insert on table "public"."player_statistics" to "anon";

grant references on table "public"."player_statistics" to "anon";

grant select on table "public"."player_statistics" to "anon";

grant trigger on table "public"."player_statistics" to "anon";

grant truncate on table "public"."player_statistics" to "anon";

grant update on table "public"."player_statistics" to "anon";

grant delete on table "public"."player_statistics" to "authenticated";

grant insert on table "public"."player_statistics" to "authenticated";

grant references on table "public"."player_statistics" to "authenticated";

grant select on table "public"."player_statistics" to "authenticated";

grant trigger on table "public"."player_statistics" to "authenticated";

grant truncate on table "public"."player_statistics" to "authenticated";

grant update on table "public"."player_statistics" to "authenticated";

grant delete on table "public"."player_statistics" to "service_role";

grant insert on table "public"."player_statistics" to "service_role";

grant references on table "public"."player_statistics" to "service_role";

grant select on table "public"."player_statistics" to "service_role";

grant trigger on table "public"."player_statistics" to "service_role";

grant truncate on table "public"."player_statistics" to "service_role";

grant update on table "public"."player_statistics" to "service_role";


