-- Transfer request schema and final save/update validation.
create table public.transfer_requests (
  transfer_request_id bigint generated by default as identity primary key,
  drafted_team_id integer not null references public.drafted_teams(drafted_team_id),
  active_season text not null,
  requester_name text not null,
  requester_email text not null,
  target_gameweek integer not null check (target_gameweek between 1 and 38),
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid
);

create table public.transfer_request_items (
  transfer_request_item_id bigint generated by default as identity primary key,
  transfer_request_id bigint not null references public.transfer_requests(transfer_request_id) on delete cascade,
  transfer_number integer not null check (transfer_number between 1 and 2),
  drafted_player_id integer not null references public.drafted_players(drafted_player_id),
  player_id integer not null references public.players(player_id),
  player_out text not null,
  player_in text not null,
  unique (transfer_request_id, transfer_number)
);

create unique index transfer_requests_one_pending_per_team
on public.transfer_requests (drafted_team_id)
where status = 'pending';

alter table public.transfer_requests enable row level security;
alter table public.transfer_request_items enable row level security;

-- Requests are private workflow data. Public pages must continue to read only
-- live drafted_transfers, so anonymous clients cannot inspect pending details.
revoke all on table public.transfer_requests from anon, authenticated;
revoke all on table public.transfer_request_items from anon, authenticated;
grant select on table public.transfer_requests to authenticated;
grant update (status, reviewed_at, reviewed_by) on table public.transfer_requests to authenticated;
grant select on table public.transfer_request_items to authenticated;
grant all on table public.transfer_requests to service_role;
grant all on table public.transfer_request_items to service_role;

create policy "Authenticated users can read transfer requests"
on public.transfer_requests
for select
to authenticated
using (true);

create policy "Authenticated users can review transfer requests"
on public.transfer_requests
for update
to authenticated
using (status = 'pending')
with check (
  status in ('approved', 'rejected')
  and reviewed_at is not null
  and reviewed_by = auth.uid()
);

create policy "Authenticated users can read transfer request items"
on public.transfer_request_items
for select
to authenticated
using (true);


create or replace function public.save_transfer_request(
  p_active_season text,
  p_drafted_team_id integer,
  p_team_name text,
  p_team_key uuid,
  p_requester_name text,
  p_requester_email text,
  p_target_gameweek integer,
  p_items jsonb,
  p_transfer_request_id bigint default null
)
returns public.transfer_requests
language plpgsql
security definer
set search_path = ''
as $$
declare
  request_row public.transfer_requests;
  current_team_value numeric := 0;
  next_team_value numeric := 0;
  outgoing_cost numeric;
  incoming_cost numeric;
  outgoing_position integer;
  incoming_position integer;
  outgoing_name text;
  incoming_name text;
  incoming_unavailable boolean;
  january_first date;
  previous_period_transfers integer := 0;
  later_period_transfers integer := 0;
  current_gameweek integer;
  transfer_item record;
begin
  if p_target_gameweek not between 1 and 38 then
    raise exception 'Invalid target gameweek';
  end if;

  if jsonb_array_length(p_items) not between 1 and 2 then
    raise exception 'A transfer request must contain one or two transfers';
  end if;

  if exists (
    select 1
    from jsonb_to_recordset(p_items) as duplicate_item(drafted_player_id integer, player_id integer)
    group by duplicate_item.drafted_player_id
    having count(*) > 1
  ) or exists (
    select 1
    from jsonb_to_recordset(p_items) as duplicate_item(drafted_player_id integer, player_id integer)
    group by duplicate_item.player_id
    having count(*) > 1
  ) then
    raise exception 'A player can only be included once in a transfer request';
  end if;

  select setting_value::integer
  into current_gameweek
  from public.settings
  where setting_key = 'current_gameweek';

  if current_gameweek is null then
    raise exception 'Transfer settings are invalid';
  end if;

  if not exists (
    select 1
    from public.drafted_teams
    where drafted_team_id = p_drafted_team_id
      and active_season = p_active_season
      and allowed_transfers = true
      and key = p_team_key
      and lower(trim(team_name)) = lower(trim(p_team_name))
  ) then
    raise exception 'No eligible transfer team found';
  end if;

  if p_transfer_request_id is null then
    if p_target_gameweek <> current_gameweek + 1 then
      raise exception 'Invalid target gameweek';
    end if;

    insert into public.transfer_requests (
      drafted_team_id,
      active_season,
      requester_name,
      requester_email,
      target_gameweek
    )
    values (
      p_drafted_team_id,
      p_active_season,
      p_requester_name,
      p_requester_email,
      p_target_gameweek
    )
    returning * into request_row;
  else
    select *
    into request_row
    from public.transfer_requests
    where transfer_request_id = p_transfer_request_id
      and drafted_team_id = p_drafted_team_id
      and active_season = p_active_season
      and status = 'pending'
    for update;

    if request_row.transfer_request_id is null then
      raise exception 'Transfer request not found';
    end if;

    if request_row.target_gameweek <= current_gameweek then
      raise exception 'Transfer request deadline has passed';
    end if;
  end if;

  for transfer_item in
    select * from jsonb_to_recordset(p_items) as transfers(
      transfer_number integer,
      drafted_player_id integer,
      player_id integer,
      player_out text,
      player_in text
    )
  loop
    select
      current_player.cost,
      current_player.position,
      incoming_player.cost,
      incoming_player.position,
      current_player.web_name,
      incoming_player.web_name,
      coalesce(incoming_player.unavailable_for_season, false)
    into outgoing_cost, outgoing_position, incoming_cost, incoming_position,
      outgoing_name, incoming_name, incoming_unavailable
    from public.drafted_players drafted_player
    left join lateral (
      select transfer.player_id
      from public.drafted_transfers transfer
      where transfer.drafted_player = drafted_player.drafted_player_id
      order by transfer.transfer_week desc, transfer.drafted_transfer_id desc
      limit 1
    ) latest_transfer on true
    join public.players_view current_player
      on current_player.player_id = coalesce(latest_transfer.player_id, drafted_player.drafted_player)
    join public.players_view incoming_player
      on incoming_player.player_id = transfer_item.player_id
    where drafted_player.drafted_player_id = transfer_item.drafted_player_id
      and drafted_player.drafted_team = request_row.drafted_team_id;

    if outgoing_cost is null or incoming_cost is null then
      raise exception 'One or more selected players could not be found for this team';
    end if;

    if incoming_unavailable then
      raise exception 'Incoming players are unavailable for the season';
    end if;

    if outgoing_position <> incoming_position then
      raise exception 'Incoming players must play in the same position as the outgoing player';
    end if;

    if lower(trim(transfer_item.player_out)) <> lower(trim(outgoing_name))
      or lower(trim(transfer_item.player_in)) <> lower(trim(incoming_name)) then
      raise exception 'Selected player details do not match the current player data';
    end if;

    if exists (
      select 1
      from public.drafted_players squad_player
      left join lateral (
        select transfer.player_id
        from public.drafted_transfers transfer
        where transfer.drafted_player = squad_player.drafted_player_id
        order by transfer.transfer_week desc, transfer.drafted_transfer_id desc
        limit 1
      ) latest_squad_transfer on true
      join public.players_view squad_current_player
        on squad_current_player.player_id = coalesce(latest_squad_transfer.player_id, squad_player.drafted_player)
      where squad_player.drafted_team = request_row.drafted_team_id
        and squad_current_player.player_id = transfer_item.player_id
    ) then
      raise exception 'Incoming players must not already be in the selected team';
    end if;
  end loop;

  select coalesce(sum(current_player.cost), 0)
  into current_team_value
  from public.drafted_players drafted_player
  left join lateral (
    select transfer.player_id
    from public.drafted_transfers transfer
    where transfer.drafted_player = drafted_player.drafted_player_id
    order by transfer.transfer_week desc, transfer.drafted_transfer_id desc
    limit 1
  ) latest_transfer on true
  join public.players_view current_player
    on current_player.player_id = coalesce(latest_transfer.player_id, drafted_player.drafted_player)
  where drafted_player.drafted_team = request_row.drafted_team_id;

  next_team_value := current_team_value;
  for transfer_item in
    select * from jsonb_to_recordset(p_items) as transfers(
      transfer_number integer,
      drafted_player_id integer,
      player_id integer,
      player_out text,
      player_in text
    )
  loop
    select current_player.cost, incoming_player.cost
    into outgoing_cost, incoming_cost
    from public.drafted_players drafted_player
    left join lateral (
      select transfer.player_id
      from public.drafted_transfers transfer
      where transfer.drafted_player = drafted_player.drafted_player_id
      order by transfer.transfer_week desc, transfer.drafted_transfer_id desc
      limit 1
    ) latest_transfer on true
    join public.players_view current_player
      on current_player.player_id = coalesce(latest_transfer.player_id, drafted_player.drafted_player)
    join public.players_view incoming_player
      on incoming_player.player_id = transfer_item.player_id
    where drafted_player.drafted_player_id = transfer_item.drafted_player_id
      and drafted_player.drafted_team = request_row.drafted_team_id;

    next_team_value := next_team_value - outgoing_cost + incoming_cost;
  end loop;

  if next_team_value > 85 then
    raise exception 'The requested transfers exceed the team budget';
  end if;

  january_first := make_date(
    2000 + split_part(request_row.active_season, '-', 2)::integer,
    1,
    1
  );

  select count(*)
  into previous_period_transfers
  from public.drafted_transfers transfer
  join public.drafted_players drafted_player on drafted_player.drafted_player_id = transfer.drafted_player
  where drafted_player.drafted_team = request_row.drafted_team_id
    and (transfer.created_at at time zone 'Europe/London')::date < january_first;

  select count(*)
  into later_period_transfers
  from public.drafted_transfers transfer
  join public.drafted_players drafted_player on drafted_player.drafted_player_id = transfer.drafted_player
  where drafted_player.drafted_team = request_row.drafted_team_id
    and (transfer.created_at at time zone 'Europe/London')::date >= january_first;

  if (request_row.created_at at time zone 'Europe/London')::date < january_first
    and previous_period_transfers + jsonb_array_length(p_items) > 2 then
    raise exception 'This team has already used its two transfers before 1 January';
  end if;

  if (request_row.created_at at time zone 'Europe/London')::date >= january_first
    and later_period_transfers + jsonb_array_length(p_items) > 2 then
    raise exception 'This team has already used its two transfers after 1 January';
  end if;

  if p_transfer_request_id is not null then
    update public.transfer_requests
    set
      requester_name = p_requester_name,
      requester_email = p_requester_email
    where transfer_request_id = request_row.transfer_request_id
    returning * into request_row;

    delete from public.transfer_request_items
    where transfer_request_id = request_row.transfer_request_id;
  end if;

  insert into public.transfer_request_items (
    transfer_request_id,
    transfer_number,
    drafted_player_id,
    player_id,
    player_out,
    player_in
  )
  select
    request_row.transfer_request_id,
    request_item.transfer_number,
    request_item.drafted_player_id,
    request_item.player_id,
    request_item.player_out,
    request_item.player_in
  from jsonb_to_recordset(p_items) as request_item(
    transfer_number integer,
    drafted_player_id integer,
    player_id integer,
    player_out text,
    player_in text
  );

  return request_row;
exception
  when unique_violation then
    raise exception 'A transfer request is already pending for this team';
end;
$$;

revoke all on function public.save_transfer_request(text, integer, text, uuid, text, text, integer, jsonb, bigint)
from public, anon, authenticated;
grant execute on function public.save_transfer_request(text, integer, text, uuid, text, text, integer, jsonb, bigint)
to service_role;
