create table public.seasons (
  id bigint generated by default as identity primary key,
  season_key text not null unique,
  display_name text not null,
  final_gameweek smallint not null,
  archived_at timestamp with time zone,
  created_at timestamp with time zone not null default now(),
  constraint seasons_key_format_check
    check (season_key ~ '^[0-9]{2}-[0-9]{2}$'),
  constraint seasons_display_name_not_blank_check
    check (btrim(display_name) <> ''),
  constraint seasons_final_gameweek_check
    check (final_gameweek between 1 and 38)
);

create table public.season_results (
  id bigint generated by default as identity primary key,
  season_id bigint not null,
  team_name text not null,
  owner_display_name text not null,
  final_position smallint not null,
  final_score integer not null,
  constraint season_results_season_id_fkey
    foreign key (season_id)
    references public.seasons(id)
    on delete restrict,
  constraint season_results_team_name_not_blank_check
    check (btrim(team_name) <> ''),
  constraint season_results_owner_name_not_blank_check
    check (btrim(owner_display_name) <> ''),
  constraint season_results_final_position_check
    check (final_position > 0),
  constraint season_results_position_unique
    unique (season_id, final_position)
);

create table public.season_result_players (
  id bigint generated by default as identity primary key,
  season_result_id bigint not null,
  squad_order smallint not null,
  player_display_name text not null,
  position text not null,
  club_name text not null,
  club_short_name text not null,
  constraint season_result_players_result_id_fkey
    foreign key (season_result_id)
    references public.season_results(id)
    on delete restrict,
  constraint season_result_players_squad_order_check
    check (squad_order between 1 and 11),
  constraint season_result_players_name_not_blank_check
    check (btrim(player_display_name) <> ''),
  constraint season_result_players_position_check
    check (position in ('goalkeeper', 'defender', 'midfielder', 'forward')),
  constraint season_result_players_club_name_not_blank_check
    check (btrim(club_name) <> ''),
  constraint season_result_players_club_short_name_not_blank_check
    check (btrim(club_short_name) <> ''),
  constraint season_result_players_squad_order_unique
    unique (season_result_id, squad_order)
);

create table public.season_result_transfers (
  id bigint generated by default as identity primary key,
  season_result_id bigint not null,
  gameweek smallint not null,
  transfer_order smallint not null,
  outgoing_player_display_name text not null,
  outgoing_club_name text not null,
  outgoing_club_short_name text not null,
  incoming_player_display_name text not null,
  incoming_club_name text not null,
  incoming_club_short_name text not null,
  constraint season_result_transfers_result_id_fkey
    foreign key (season_result_id)
    references public.season_results(id)
    on delete restrict,
  constraint season_result_transfers_gameweek_check
    check (gameweek between 1 and 38),
  constraint season_result_transfers_order_check
    check (transfer_order > 0),
  constraint season_result_transfers_outgoing_name_not_blank_check
    check (btrim(outgoing_player_display_name) <> ''),
  constraint season_result_transfers_outgoing_club_name_not_blank_check
    check (btrim(outgoing_club_name) <> ''),
  constraint season_transfers_out_club_short_not_blank_check
    check (btrim(outgoing_club_short_name) <> ''),
  constraint season_result_transfers_incoming_name_not_blank_check
    check (btrim(incoming_player_display_name) <> ''),
  constraint season_result_transfers_incoming_club_name_not_blank_check
    check (btrim(incoming_club_name) <> ''),
  constraint season_transfers_in_club_short_not_blank_check
    check (btrim(incoming_club_short_name) <> ''),
  constraint season_result_transfers_order_unique
    unique (season_result_id, transfer_order)
);

comment on table public.seasons is
  'Catalogue of league seasons. A non-null archived_at marks a completed immutable snapshot.';

comment on table public.season_results is
  'Final fantasy-team standings copied for display without private or operational team data.';

comment on table public.season_result_players is
  'Final Squad display snapshot independent of live FPL player and club identifiers.';

comment on table public.season_result_transfers is
  'Ordered outgoing-to-incoming transfer display snapshot independent of live FPL identifiers.';

create or replace function public.reject_archived_season_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if old.archived_at is not null then
    raise exception 'Archived Season snapshots are read-only';
  end if;

  if tg_op = 'DELETE' then
    return old;
  end if;

  return new;
end;
$$;

create or replace function public.reject_archived_snapshot_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  old_season_id bigint;
  new_season_id bigint;
begin
  if tg_table_name = 'season_results' then
    if tg_op <> 'INSERT' then
      old_season_id := old.season_id;
    end if;

    if tg_op <> 'DELETE' then
      new_season_id := new.season_id;
    end if;
  else
    if tg_op <> 'INSERT' then
      select sr.season_id
      into old_season_id
      from public.season_results sr
      where sr.id = old.season_result_id;
    end if;

    if tg_op <> 'DELETE' then
      select sr.season_id
      into new_season_id
      from public.season_results sr
      where sr.id = new.season_result_id;
    end if;
  end if;

  if exists (
    select 1
    from public.seasons s
    where s.id in (old_season_id, new_season_id)
      and s.archived_at is not null
  ) then
    raise exception 'Archived Season snapshots are read-only';
  end if;

  if tg_op = 'DELETE' then
    return old;
  end if;

  return new;
end;
$$;

create trigger reject_archived_season_change
before update or delete on public.seasons
for each row execute function public.reject_archived_season_change();

create trigger reject_archived_result_change
before insert or update or delete on public.season_results
for each row execute function public.reject_archived_snapshot_change();

create trigger reject_archived_player_change
before insert or update or delete on public.season_result_players
for each row execute function public.reject_archived_snapshot_change();

create trigger reject_archived_transfer_change
before insert or update or delete on public.season_result_transfers
for each row execute function public.reject_archived_snapshot_change();

alter table public.seasons enable row level security;
alter table public.season_results enable row level security;
alter table public.season_result_players enable row level security;
alter table public.season_result_transfers enable row level security;

create policy "Completed Seasons are publicly readable"
on public.seasons
for select
using (archived_at is not null);

create policy "Completed Season Results are publicly readable"
on public.season_results
for select
using (
  exists (
    select 1
    from public.seasons s
    where s.id = season_results.season_id
      and s.archived_at is not null
  )
);

create policy "Completed Final Squads are publicly readable"
on public.season_result_players
for select
using (
  exists (
    select 1
    from public.season_results sr
    join public.seasons s on s.id = sr.season_id
    where sr.id = season_result_players.season_result_id
      and s.archived_at is not null
  )
);

create policy "Completed Season Transfers are publicly readable"
on public.season_result_transfers
for select
using (
  exists (
    select 1
    from public.season_results sr
    join public.seasons s on s.id = sr.season_id
    where sr.id = season_result_transfers.season_result_id
      and s.archived_at is not null
  )
);

revoke all on table public.seasons from anon, authenticated, service_role;
revoke all on table public.season_results from anon, authenticated, service_role;
revoke all on table public.season_result_players from anon, authenticated, service_role;
revoke all on table public.season_result_transfers from anon, authenticated, service_role;

grant select on table public.seasons to anon, authenticated, service_role;
grant select on table public.season_results to anon, authenticated, service_role;
grant select on table public.season_result_players to anon, authenticated, service_role;
grant select on table public.season_result_transfers to anon, authenticated, service_role;

revoke all on function public.reject_archived_season_change()
from public, anon, authenticated, service_role;

revoke all on function public.reject_archived_snapshot_change()
from public, anon, authenticated, service_role;

create or replace function public.archive_completed_season(
  source_season_key text,
  archive_display_name text,
  final_gameweek integer
)
returns table (
  season_id bigint,
  team_count integer,
  player_count integer,
  transfer_count integer
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  archived_season_id bigint;
  source_team_count integer;
  source_player_count integer;
  source_transfer_count integer;
  archived_team_count integer;
  archived_player_count integer;
  archived_transfer_count integer;
begin
  if source_season_key is null
    or source_season_key !~ '^[0-9]{2}-[0-9]{2}$'
  then
    raise exception 'Season key must use the YY-YY format';
  end if;

  if archive_display_name is null
    or btrim(archive_display_name) = ''
  then
    raise exception 'Season display name must not be blank';
  end if;

  if final_gameweek is null
    or final_gameweek not between 1 and 38
  then
    raise exception 'Final gameweek must be between 1 and 38';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(source_season_key, 0)
  );

  lock table
    public.drafted_teams,
    public.drafted_players,
    public.drafted_transfers,
    public.weekly_statistics,
    public.players,
    public.teams
  in share mode;

  if exists (
    select 1
    from public.seasons s
    where s.season_key = source_season_key
  ) then
    raise exception 'Season % has already been archived', source_season_key;
  end if;

  select count(*)::integer
  into source_team_count
  from public.drafted_teams dt
  where dt.active_season = source_season_key;

  if source_team_count = 0 then
    raise exception 'Season % has no fantasy teams to archive', source_season_key;
  end if;

  if exists (
    select 1
    from public.drafted_teams dt
    where dt.active_season = source_season_key
      and (
        btrim(dt.team_name) = ''
        or btrim(dt.team_owner) = ''
      )
  ) then
    raise exception 'Season % has a blank team or owner display name',
      source_season_key;
  end if;

  if exists (
    select 1
    from public.drafted_teams dt
    join public.drafted_players dp
      on dp.drafted_team = dt.drafted_team_id
    where dt.active_season = source_season_key
    group by dt.drafted_team_id
    having count(*) <> 11
  )
  or exists (
    select 1
    from public.drafted_teams dt
    where dt.active_season = source_season_key
      and not exists (
        select 1
        from public.drafted_players dp
        where dp.drafted_team = dt.drafted_team_id
      )
  ) then
    raise exception 'Every fantasy team in Season % must have exactly 11 drafted slots',
      source_season_key;
  end if;

  if exists (
    select 1
    from public.drafted_teams dt
    where dt.active_season = source_season_key
      and not exists (
        select 1
        from public.weekly_statistics ws
        where ws.team = dt.drafted_team_id
          and ws.week = final_gameweek
      )
  ) then
    raise exception 'Every fantasy team in Season % must have statistics for gameweek %',
      source_season_key,
      final_gameweek;
  end if;

  if exists (
    select 1
    from public.drafted_teams dt
    join public.weekly_statistics ws
      on ws.team = dt.drafted_team_id
    where dt.active_season = source_season_key
      and ws.week > final_gameweek
  ) then
    raise exception 'Season % has statistics after final gameweek %',
      source_season_key,
      final_gameweek;
  end if;

  if exists (
    select 1
    from public.drafted_teams dt
    join public.drafted_players dp
      on dp.drafted_team = dt.drafted_team_id
    join public.drafted_transfers transfer_record
      on transfer_record.drafted_player = dp.drafted_player_id
    where dt.active_season = source_season_key
      and (
        transfer_record.transfer_week is null
        or transfer_record.transfer_week not between 1 and final_gameweek
      )
  ) then
    raise exception 'Season % has a transfer outside gameweeks 1 to %',
      source_season_key,
      final_gameweek;
  end if;

  if exists (
    select 1
    from (
      select
        dp.drafted_player_id,
        coalesce(latest_transfer.player_id, dp.drafted_player) as final_player_id
      from public.drafted_teams dt
      join public.drafted_players dp
        on dp.drafted_team = dt.drafted_team_id
      left join lateral (
        select transfer_record.player_id
        from public.drafted_transfers transfer_record
        where transfer_record.drafted_player = dp.drafted_player_id
        order by
          transfer_record.transfer_week desc,
          transfer_record.created_at desc,
          transfer_record.drafted_transfer_id desc
        limit 1
      ) latest_transfer on true
      where dt.active_season = source_season_key
    ) final_slots
    left join public.players p
      on p.player_id = final_slots.final_player_id
    left join public.teams club
      on club.id = p.team
    where p.player_id is null
      or p.web_name is null
      or btrim(p.web_name) = ''
      or p.element_type not between 1 and 4
      or club.id is null
      or club.name is null
      or btrim(club.name) = ''
      or club.short_name is null
      or btrim(club.short_name) = ''
  ) then
    raise exception 'Season % has an unresolved Final Squad player or club',
      source_season_key;
  end if;

  if exists (
    select 1
    from public.drafted_teams dt
    join public.drafted_players dp
      on dp.drafted_team = dt.drafted_team_id
    join public.drafted_transfers transfer_record
      on transfer_record.drafted_player = dp.drafted_player_id
    left join public.players incoming_player
      on incoming_player.player_id = transfer_record.player_id
    left join public.teams incoming_club
      on incoming_club.id = incoming_player.team
    where dt.active_season = source_season_key
      and (
        incoming_player.player_id is null
        or incoming_player.web_name is null
        or btrim(incoming_player.web_name) = ''
        or incoming_club.id is null
        or incoming_club.name is null
        or btrim(incoming_club.name) = ''
        or incoming_club.short_name is null
        or btrim(incoming_club.short_name) = ''
      )
  ) then
    raise exception 'Season % has an unresolved incoming transfer player or club',
      source_season_key;
  end if;

  if exists (
    with ordered_transfers as (
      select
        dt.drafted_team_id,
        dp.drafted_player_id,
        dp.drafted_player as original_player_id,
        transfer_record.player_id as incoming_player_id,
        lag(transfer_record.player_id) over (
          partition by dp.drafted_player_id
          order by
            transfer_record.transfer_week,
            transfer_record.created_at,
            transfer_record.drafted_transfer_id
        ) as previous_incoming_player_id
      from public.drafted_teams dt
      join public.drafted_players dp
        on dp.drafted_team = dt.drafted_team_id
      join public.drafted_transfers transfer_record
        on transfer_record.drafted_player = dp.drafted_player_id
      where dt.active_season = source_season_key
    )
    select 1
    from ordered_transfers ordered_transfer
    left join public.players outgoing_player
      on outgoing_player.player_id = coalesce(
        ordered_transfer.previous_incoming_player_id,
        ordered_transfer.original_player_id
      )
    left join public.teams outgoing_club
      on outgoing_club.id = outgoing_player.team
    where outgoing_player.player_id is null
      or outgoing_player.web_name is null
      or btrim(outgoing_player.web_name) = ''
      or outgoing_club.id is null
      or outgoing_club.name is null
      or btrim(outgoing_club.name) = ''
      or outgoing_club.short_name is null
      or btrim(outgoing_club.short_name) = ''
  ) then
    raise exception 'Season % has an unresolved outgoing transfer player or club',
      source_season_key;
  end if;

  if exists (
    with final_slots as (
      select
        dt.drafted_team_id,
        coalesce(latest_transfer.player_id, dp.drafted_player) as final_player_id
      from public.drafted_teams dt
      join public.drafted_players dp
        on dp.drafted_team = dt.drafted_team_id
      left join lateral (
        select transfer_record.player_id
        from public.drafted_transfers transfer_record
        where transfer_record.drafted_player = dp.drafted_player_id
        order by
          transfer_record.transfer_week desc,
          transfer_record.created_at desc,
          transfer_record.drafted_transfer_id desc
        limit 1
      ) latest_transfer on true
      where dt.active_season = source_season_key
    )
    select 1
    from final_slots fs
    join public.players p on p.player_id = fs.final_player_id
    group by fs.drafted_team_id
    having
      count(*) filter (where p.element_type = 1) <> 1
      or count(*) filter (where p.element_type = 2) <> 4
      or count(*) filter (where p.element_type = 3) <> 3
      or count(*) filter (where p.element_type = 4) <> 3
  ) then
    raise exception 'Every Final Squad in Season % must use the 1/4/3/3 formation',
      source_season_key;
  end if;

  if exists (
    select 1
    from public.drafted_teams dt
    join public.drafted_players dp
      on dp.drafted_team = dt.drafted_team_id
    join public.drafted_transfers transfer_record
      on transfer_record.drafted_player = dp.drafted_player_id
    where dt.active_season = source_season_key
    group by dt.drafted_team_id
    having count(*) > 32767
  ) then
    raise exception 'Season % has too many transfers for one fantasy team',
      source_season_key;
  end if;

  insert into public.seasons (
    season_key,
    display_name,
    final_gameweek
  )
  values (
    source_season_key,
    archive_display_name,
    final_gameweek
  )
  returning id into archived_season_id;

  with ranked_teams as (
    select
      dt.drafted_team_id,
      dt.team_name,
      dt.team_owner,
      sum(ws.points)::integer as final_score,
      row_number() over (
        order by
          sum(ws.points) desc,
          coalesce(sum(ws.goals), 0) desc,
          dt.drafted_team_id
      )::smallint as final_position
    from public.drafted_teams dt
    join public.weekly_statistics ws
      on ws.team = dt.drafted_team_id
    where dt.active_season = source_season_key
      and ws.week <= final_gameweek
    group by
      dt.drafted_team_id,
      dt.team_name,
      dt.team_owner
  )
  insert into public.season_results (
    season_id,
    team_name,
    owner_display_name,
    final_position,
    final_score
  )
  select
    archived_season_id,
    ranked_team.team_name,
    ranked_team.team_owner,
    ranked_team.final_position,
    ranked_team.final_score
  from ranked_teams ranked_team;

  with ranked_teams as (
    select
      dt.drafted_team_id,
      row_number() over (
        order by
          sum(ws.points) desc,
          coalesce(sum(ws.goals), 0) desc,
          dt.drafted_team_id
      )::smallint as final_position
    from public.drafted_teams dt
    join public.weekly_statistics ws
      on ws.team = dt.drafted_team_id
    where dt.active_season = source_season_key
      and ws.week <= final_gameweek
    group by dt.drafted_team_id
  ),
  final_slots as (
    select
      dt.drafted_team_id,
      dp.drafted_player_id,
      coalesce(latest_transfer.player_id, dp.drafted_player) as final_player_id
    from public.drafted_teams dt
    join public.drafted_players dp
      on dp.drafted_team = dt.drafted_team_id
    left join lateral (
      select transfer_record.player_id
      from public.drafted_transfers transfer_record
      where transfer_record.drafted_player = dp.drafted_player_id
      order by
        transfer_record.transfer_week desc,
        transfer_record.created_at desc,
        transfer_record.drafted_transfer_id desc
      limit 1
    ) latest_transfer on true
    where dt.active_season = source_season_key
  ),
  ordered_final_slots as (
    select
      fs.drafted_team_id,
      fs.final_player_id,
      row_number() over (
        partition by fs.drafted_team_id
        order by p.element_type, fs.drafted_player_id
      )::smallint as squad_order
    from final_slots fs
    join public.players p on p.player_id = fs.final_player_id
  )
  insert into public.season_result_players (
    season_result_id,
    squad_order,
    player_display_name,
    position,
    club_name,
    club_short_name
  )
  select
    sr.id,
    ofs.squad_order,
    p.web_name,
    case p.element_type
      when 1 then 'goalkeeper'
      when 2 then 'defender'
      when 3 then 'midfielder'
      when 4 then 'forward'
    end,
    club.name,
    club.short_name
  from ordered_final_slots ofs
  join ranked_teams ranked_team
    on ranked_team.drafted_team_id = ofs.drafted_team_id
  join public.season_results sr
    on sr.season_id = archived_season_id
    and sr.final_position = ranked_team.final_position
  join public.players p
    on p.player_id = ofs.final_player_id
  join public.teams club
    on club.id = p.team;

  with ranked_teams as (
    select
      dt.drafted_team_id,
      row_number() over (
        order by
          sum(ws.points) desc,
          coalesce(sum(ws.goals), 0) desc,
          dt.drafted_team_id
      )::smallint as final_position
    from public.drafted_teams dt
    join public.weekly_statistics ws
      on ws.team = dt.drafted_team_id
    where dt.active_season = source_season_key
      and ws.week <= final_gameweek
    group by dt.drafted_team_id
  ),
  transfer_chain as (
    select
      dt.drafted_team_id,
      transfer_record.transfer_week,
      transfer_record.created_at,
      transfer_record.drafted_transfer_id,
      transfer_record.player_id as incoming_player_id,
      coalesce(
        lag(transfer_record.player_id) over (
          partition by dp.drafted_player_id
          order by
            transfer_record.transfer_week,
            transfer_record.created_at,
            transfer_record.drafted_transfer_id
        ),
        dp.drafted_player
      ) as outgoing_player_id
    from public.drafted_teams dt
    join public.drafted_players dp
      on dp.drafted_team = dt.drafted_team_id
    join public.drafted_transfers transfer_record
      on transfer_record.drafted_player = dp.drafted_player_id
    where dt.active_season = source_season_key
  ),
  ordered_team_transfers as (
    select
      tc.*,
      row_number() over (
        partition by tc.drafted_team_id
        order by
          tc.transfer_week,
          tc.created_at,
          tc.drafted_transfer_id
      )::smallint as transfer_order
    from transfer_chain tc
  )
  insert into public.season_result_transfers (
    season_result_id,
    gameweek,
    transfer_order,
    outgoing_player_display_name,
    outgoing_club_name,
    outgoing_club_short_name,
    incoming_player_display_name,
    incoming_club_name,
    incoming_club_short_name
  )
  select
    sr.id,
    ott.transfer_week::smallint,
    ott.transfer_order,
    outgoing_player.web_name,
    outgoing_club.name,
    outgoing_club.short_name,
    incoming_player.web_name,
    incoming_club.name,
    incoming_club.short_name
  from ordered_team_transfers ott
  join ranked_teams ranked_team
    on ranked_team.drafted_team_id = ott.drafted_team_id
  join public.season_results sr
    on sr.season_id = archived_season_id
    and sr.final_position = ranked_team.final_position
  join public.players outgoing_player
    on outgoing_player.player_id = ott.outgoing_player_id
  join public.teams outgoing_club
    on outgoing_club.id = outgoing_player.team
  join public.players incoming_player
    on incoming_player.player_id = ott.incoming_player_id
  join public.teams incoming_club
    on incoming_club.id = incoming_player.team;

  select count(*)::integer
  into source_player_count
  from public.drafted_teams dt
  join public.drafted_players dp
    on dp.drafted_team = dt.drafted_team_id
  where dt.active_season = source_season_key;

  select count(*)::integer
  into source_transfer_count
  from public.drafted_teams dt
  join public.drafted_players dp
    on dp.drafted_team = dt.drafted_team_id
  join public.drafted_transfers transfer_record
    on transfer_record.drafted_player = dp.drafted_player_id
  where dt.active_season = source_season_key;

  select count(*)::integer
  into archived_team_count
  from public.season_results sr
  where sr.season_id = archived_season_id;

  select count(*)::integer
  into archived_player_count
  from public.season_result_players srp
  join public.season_results sr
    on sr.id = srp.season_result_id
  where sr.season_id = archived_season_id;

  select count(*)::integer
  into archived_transfer_count
  from public.season_result_transfers srt
  join public.season_results sr
    on sr.id = srt.season_result_id
  where sr.season_id = archived_season_id;

  if archived_team_count <> source_team_count
    or archived_player_count <> source_player_count
    or archived_transfer_count <> source_transfer_count
  then
    raise exception 'Season % archive count validation failed', source_season_key;
  end if;

  if exists (
    select 1
    from public.season_results sr
    left join public.season_result_players srp
      on srp.season_result_id = sr.id
    where sr.season_id = archived_season_id
    group by sr.id
    having
      count(*) <> 11
      or count(*) filter (where srp.position = 'goalkeeper') <> 1
      or count(*) filter (where srp.position = 'defender') <> 4
      or count(*) filter (where srp.position = 'midfielder') <> 3
      or count(*) filter (where srp.position = 'forward') <> 3
  ) then
    raise exception 'Season % archived Final Squad validation failed',
      source_season_key;
  end if;

  update public.seasons
  set archived_at = clock_timestamp()
  where id = archived_season_id;

  return query
  select
    archived_season_id,
    archived_team_count,
    archived_player_count,
    archived_transfer_count;
end;
$$;

comment on function public.archive_completed_season(text, text, integer) is
  'Owner-only explicit operation that validates and publishes an immutable completed Season snapshot without deleting operational data.';

revoke all on function public.archive_completed_season(text, text, integer)
from public, anon, authenticated, service_role;
